### ISSUE TITLE
Docs: manual-dependencies.md incorrect

### ISSUE THREAD

**Issue by thernstig** [fossas/fossa-cli#1027]
https://github.com/fossas/fossa-cli/blob/master/docs/features/manual-dependencies.md has a few problems:

- Examples still use https://github.com/fossas/spectrometer in the URL. It should be https://github.com/fossas/fossa-cli instead.
- For `referenced-dependencies` several dependency types are listed that is not part of the JSON schema found at https://raw.githubusercontent.com/fossas/fossa-cli/master/docs/references/files/fossa-deps.schema.json. Either/or needs to be updated.
- There is some error in https://raw.githubusercontent.com/fossas/fossa-cli/master/docs/references/files/fossa-deps.schema.json. Try to create a fossa-deps.yaml with this content (notice the error (red squiggly lines):
```yaml
remote-dependencies:
  - name: Node.js
    version: "16.14.2"
    url: https://github.com/nodejs/node/archive/refs/tags/v16.14.2.tar.gz
```
