### ISSUE TITLE
Allow users to pass arbitrary options to builders

### ISSUE THREAD

**Issue by ilikebits** [fossas/fossa-cli#120]
Some builders require extra non-standard configuration. Some examples:

- [ ] Gradle: users can specify non-standard default task names
- [ ] Python: users can specify non-standard (or multiple) `requirements.txt` filepaths

Users should be able to specify these on both the command line and the configuration file. The syntax I'm thinking of for now:

Via `.fossa.yml`:
```yaml
analyze:
  modules:
  - name: example-pip
    path: path/to/python/project
    type: pip
    options:
      manifests: ['dev-requirements.txt', 'prod-requirements.txt']
```

Via the command line:
```bash
# name:type:path[:<...key=val>]
fossa analyze --modules example-pip:pip:path/to/python/project:manifests=['dev-requirements.txt', 'prod-requirements.txt']:foo=bar
```
