### ISSUE TITLE
PNPM analyses 

### ISSUE THREAD

**Issue by ivanmjartan** [fossas/fossa-cli#1391]
Hello guys I am trying to run fossa scan on our [public repository](https://github.com/gooddata/gooddata-ui-sdk/) and I am preforming scan only on top of [pnpm-lock.yam](https://github.com/gooddata/gooddata-ui-sdk/blob/master/common/config/rush/pnpm-lock.yaml)l file. We are using RUSH as monorep tool. 

So I have setting in my repo .fosss.yml 

Problem is that part of my monorepo is also tooling library and tooling dependency occurred in attribution file. 

Is there way how to exclude some packages from scan if I am performing scan only on top of pnpm lock file ? 

for example in my lock file is this tool package https://github.com/gooddata/gooddata-ui-sdk/blob/master/common/config/rush/pnpm-lock.yaml#L5893C3-L5893C22

How can I set it into .fossa.yml

this part of code is not working and scan contain still all dep from pnpm-lock.yaml  

```
version: 3
project:
  id: gooddata-ui-sdk

telemetry:
  scope: 'off'

targets:
  only:
    - type: pnpm
      path: common/config/rush
  exclude:
    - type: bundler
      path: ../../tools/applink
```

Thanks very much for hints
