### ISSUE TITLE
[BUG] experimentalKeywordSearch results not shown in the UI

### ISSUE THREAD

**Issue by jandroav** [fossas/fossa-cli#1397]
**Describe the bug**
I configured a project as shown here: [Custom-License and Keyword Searches](https://github.com/fossas/fossa-cli/blob/master/docs/features/custom-license-and-keyword-searches.md) to detect AI-generated code, but I can not see the result in the FOSSA UI as shown during this video [Managing GitHub Copilot Security and Legal Risks with FOSSA](https://www.brighttalk.com/webcast/17752/593382?bt_tok=%7B%7Blead.Id%7D%7D) (min 47)

**To Reproduce**
1. Create a `.fossa.yml` file with:
  ```yml
  version: 3
  
  experimentalKeywordSearch:
    - matchCriteria: "Copilot"
      name: "GitHub Copilot generated code"
  ```
2. Tag some code as with the `Copilot` tag:

```go
// Copilot
// Checks if the user has the required tools installed
func CheckInstalledTools(tool string) error {...}
```

3. Run `fossa analyze`
4. Results are correctly shown but no UI section:
![image](https://github.com/fossas/fossa-cli/assets/67458478/014d8435-db98-4dd5-a90d-b38922a8716e)

**Expected behavior**
A FOSSA UI section with the matches

[fossa.debug.json.gz](https://github.com/fossas/fossa-cli/files/14666105/fossa.debug.json.gz)
