### ISSUE TITLE
[QUESTION] Can you use pattern matching in targets.exclude?

### ISSUE THREAD

**Issue by thecristidima** [fossas/fossa-cli#1487]
We would like to exclude all test projects in our repo and tried the following:
```
version: 3

paths:
  only:
    - ./Code

  exclude:
    - ./Code/**/*Tests

```

but we get the following error:

```
Aeson exception:
Error in $.paths.exclude[6]: InvalidRelDir "./**/*Tests"
```

Taking a look at https://github.com/fossas/fossa-cli/blob/master/docs/references/files/fossa-yml.md#fossayml it seems that we can use pattern matching for paths, but it's not used under paths.only/exclude, so I'm not quite sure if it works or not.
