### ISSUE TITLE
test.sh broken: no revision found for package name error on analyze with unedited init for hashicorp/consul

### ISSUE THREAD

**Issue by microsoftly** [fossas/fossa-cli#280]
**Describe the bug**
`fossa analyze` fails on `github.com/hashicorp/consul` when it should not return an error (I do not know the exact expected output at the moment)

**To Reproduce**
1. `go get -u -v github.com/hashicorp/consul`
2. `fossa init`
3. `fossa analyze -o --option allow-nested-vendor:true --option allow-deep-vendor:true go:.`
4. See error, expected to be `FATAL Could not analyze: no revision found for package name`

**Expected behavior**
successful output with package analysis

**Debugging information**
`
DEBUG Could not find revision for package "cloud.google.com/go/compute/metadata" callers=[/home/fossa/go/src/github.com/fossas/fossa-cli/analyzers/golang/revision.go:github.com/fossas/fossa-cli/analyzers/golang.(*Analyzer).RevisionDirect:34 /home/fossa/go/src/github.com/fossas/fossa-cli/analyzers/golang/revision.go:github.com/fossas/fossa-cli/analyzers/golang.(*Analyzer).Revision:22 /home/fossa/go/src/github.com/fossas/fossa-cli/analyzers/golang/analyze.go:github.com/fossas/fossa-cli/analyzers/golang.(*Analyzer).Analyze:131 /home/fossa/go/src/github.com/fossas/fossa-cli/cmd/fossa/cmd/analyze/analyze.go:github.com/fossas/fossa-cli/cmd/fossa/cmd/analyze.Do:122 /home/fossa/go/src/github.com/fossas/fossa-cli/cmd/fossa/cmd/analyze/analyze.go:github.com/fossas/fossa-cli/cmd/fossa/cmd/analyze.Run:48 /home/fossa/go/src/github.com/fossas/fossa-cli/vendor/github.com/urfave/cli/app.go:github.com/fossas/fossa-cli/vendor/github.com/urfave/cli.HandleAction:490 /home/fossa/go/src/github.com/fossas/fossa-cli/vendor/github.com/urfave/cli/command.go:github.com/fossas/fossa-cli/vendor/github.com/urfave/cli.Command.Run:210 /home/fossa/go/src/github.com/fossas/fossa-cli/vendor/github.com/urfave/cli/app.go:github.com/fossas/fossa-cli/vendor/github.com/urfave/cli.(*App).Run:255 /home/fossa/go/src/github.com/fossas/fossa-cli/cmd/fossa/main.go:main.main:47]
FATAL Could not analyze: no revision found for package name callers=[/home/fossa/go/src/github.com/fossas/fossa-cli/cmd/fossa/cmd/analyze/analyze.go:github.com/fossas/fossa-cli/cmd/fossa/cmd/analyze.Do:124 /home/fossa/go/src/github.com/fossas/fossa-cli/cmd/fossa/cmd/analyze/analyze.go:github.com/fossas/fossa-cli/cmd/fossa/cmd/analyze.Run:48 /home/fossa/go/src/github.com/fossas/fossa-cli/vendor/github.com/urfave/cli/app.go:github.com/fossas/fossa-cli/vendor/github.com/urfave/cli.HandleAction:490 /home/fossa/go/src/github.com/fossas/fossa-cli/vendor/github.com/urfave/cli/command.go:github.com/fossas/fossa-cli/vendor/github.com/urfave/cli.Command.Run:210 /home/fossa/go/src/github.com/fossas/fossa-cli/vendor/github.com/urfave/cli/app.go:github.com/fossas/fossa-cli/vendor/github.com/urfave/cli.(*App).Run:255 /home/fossa/go/src/github.com/fossas/fossa-cli/cmd/fossa/main.go:main.main:47]
`

1. The output of running the buggy command with the `--debug` flag
2. version: `0.7.7` & `master`
3. `.fossa.yml`
``` yml
version: 1
cli:
  server: https://app.fossa.io
  fetcher: custom
  project: https://github.com/hashicorp/consul
analyze:
  modules:
  - name: github.com/hashicorp/consul
    type: go
    target: github.com/hashicorp/consul
    path: /Users/Fossa/projects/go/src/github.com/hashicorp/consul
  - name: github.com/hashicorp/consul/connect/certgen
    type: go
    target: github.com/hashicorp/consul/connect/certgen
    path: /Users/Fossa/projects/go/src/github.com/hashicorp/consul/connect/certgen
  - name: startup
    type: npm
    target: ui-v2/lib/startup
    path: ui-v2/lib/startup
  - name: consul-ui
    type: npm
    target: ui-v2
    path: ui-v2
  - name: Gemfile
    type: gem
    target: ui
    path: ui
  - name: Gemfile
    type: gem
    target: website
    path: website
```

**Environment (please complete the following information):**
 - osx 10.13.6 
 - fossa-cli-test-base:97a5a641-7416-4e03-9235-cdf93ce2ef35
