### ISSUE TITLE
Trailing slash required for `npm` type modules in Provided Build

### ISSUE THREAD

**Issue by dkleissa** [fossas/fossa-cli#291]
**Describe the bug**
I was trying to configure a relatively complex repository (monorepo with python and nodejs packages) to run with Fossa. I'm doing this as a provided build in circleCI. All of the python packages were working well, but npm packages had 0 dependencies. After working locally I was able to discover that a trailing slash is required in the `path` key for a module in `.fossa.yaml`.

This requirement should either be made *much* more clear, or the CLI should be able to assume this is a dir a do a proper path join when searching for node_modules.

**To Reproduce**
1. Start with a repo containing a nodejs package
2. Configure `.fossa.yaml` like this:

```
# Generated by FOSSA CLI (https://github.com/fossas/fossa-cli)
# Visit https://fossa.io to learn more

version: 1
cli:
  server: https://app.fossa.io
  fetcher: custom
  project: my-project

analyze:
  modules:
  - name: my-node-package
    type: npm
    path: ./ui
  - name: my-python-package
    type: pip
    path: ./packages/mypackage

```

3. Run `fossa -o` and see python dependencies are found, but no dependencies are picked up for nodejs
4. Configure `.fossa.yaml` like this (*adding trailing slashes*):

```
# Generated by FOSSA CLI (https://github.com/fossas/fossa-cli)
# Visit https://fossa.io to learn more

version: 1
cli:
  server: https://app.fossa.io
  fetcher: custom
  project: my-project

analyze:
  modules:
  - name: my-node-package
    type: npm
    path: ./ui/
  - name: my-python-package
    type: pip
    path: ./packages/mypackage/

```

3. Run `fossa -o` and see all dependencies *are* picked up

**Expected behavior**
Expect a path without a trailing slash to still work

**Debugging information**
Please provide the following:

1. The output of running the buggy command with the `--debug` flag
2. The output of `fossa --version`
fossa-cli version 0.7.7 (revision e874ec2891b456ea3689825b37c278b68301bdf0 compiled with go version go1.10.3 linux/amd64)

3. The project's configuration file (usually `.fossa.yml`)
4. If possible, a minimal test case reproducing the bug (ideally, a GitHub repository)

**Environment (please complete the following information):**
 - OS: [e.g. Windows] Linux, macOS
 - Are you running in CI?: Yes, CircleCI
 - Are you running in a Docker image?: No

**Additional context**

**Comment by liftM** [comment]
Thanks for the report.

This configuration file looks like it was generated with `0.6.x`. Does this still occur with configuration files generated by `0.7.x`?

Improving documentation is something we're working hard on, thanks for bringing this up.

**Comment by dkleissa** [comment]
I re-created `.fossa.yml` using `fossa init` at `fossa-cli version 0.7.8 (revision 65a187a6460a986ac2a10446d8e3c1d15c7b4771 compiled with go version go1.10.3 linux/amd64)`

The only difference appears to be the addition of a `target` key:

```
# Generated by FOSSA CLI (https://github.com/fossas/fossa-cli)
# Visit https://fossa.io to learn more

version: 1
cli:
  server: https://app.fossa.io
  fetcher: custom
  project: my-project

analyze:
  modules:
  - name: ui
    type: npm
    target: ui
    path: ui
  - name: mypackage
    type: pip
    target: packages/mypackage
    path: packages/mypackage
```

If I run `fossa -o`, no node packages are found, python is. I then tried this:

```
# Generated by FOSSA CLI (https://github.com/fossas/fossa-cli)
# Visit https://fossa.io to learn more

version: 1
cli:
  server: https://app.fossa.io
  fetcher: custom
  project: my-project

analyze:
  modules:
  - name: ui
    type: npm
    target: ui
    path: ui/
  - name: mypackage
    type: pip
    target: packages/mypackage
    path: packages/mypackage
```

Again, if I run `fossa -o`, no node packages are found, but python is. I then tried this:

```
# Generated by FOSSA CLI (https://github.com/fossas/fossa-cli)
# Visit https://fossa.io to learn more

version: 1
cli:
  server: https://app.fossa.io
  fetcher: custom
  project: my-project

analyze:
  modules:
  - name: ui
    type: npm
    target: ui/
    path: ui/
  - name: mypackage
    type: pip
    target: packages/mypackage
    path: packages/mypackage
```

And it worked. I also tried omitting the trailing slash on the path key and it worked. So with the latest format, it looks like you need a trailing slash on target. If target is omitted, it looks like you need the trailing slash on path.
