### ISSUE TITLE
'fossa analyze' issues a warning about Leiningen analysis not running on first try.

### ISSUE THREAD

**Issue by e-gris** [fossas/fossa-cli#569]
**Describe the bug**
Running `fossa analyze` on a fresh clone of https://github.com/puppetlabs/puppetserver generates a rather stern warning:

    $ fossa analyze
    Analyzing module (1/10): project.clj WARNING FALLING BACK to parse clojure project file.
    Leiningen analysis could not be run, address the following error for more accurate results:
    Ensure that lein is installed correctly and that `lein [deps :tree]` can be run in the directory `.`

Running a second time, the warning goes away

    $ fossa analyze
    ============================================================
    View FOSSA Report:
    <link to report>
    ============================================================

**To Reproduce**

1. Install Leiningen if it isn't already.
1. Git clone https://github.com/puppetlabs/puppetserver
1. cd puppetserrver
1. Clean out ~/.m2/repository ($ rm -rf ~/.m2/repository)
1. `$ fossa init`
1. `$ fossa analyze`
1. (Notice above warning/error)
1. `$ fossa analyze`
1. (Notice warning/error is no longer present)

**Expected behavior**
Possible EB 1: The error/warning/failure is fully reproducible (not just on the first run) and produces the actual warning with hints on what went wrong (The message refers to "the following error for more accurate results" but does not produce it.)

Possible EB 2: If `lein deps tree` is, in fact, working, there should be no warning.

Side note: Part of the warning refers to the problem as a 'warning', the other as an 'error'. This should be clarified.

**Debugging information**
Please provide the following:

1. The output of running the buggy command with the `--debug` flag

    [fossa-lein-debug.txt](https://github.com/fossas/fossa-cli/files/4124800/fossa-lein-debug.txt)
    
2. The output of `fossa --version`

    $ fossa --version
    fossa-cli version 1.0.17 (revision 85a7e9c8a4ac94e72b15934e1ef071273b445cc4 compiled with go version go1.13.5 linux/amd64)

3. The project's configuration file (usually `.fossa.yml`)

```yaml
# Generated by FOSSA CLI (https://github.com/fossas/fossa-cli)
# Visit https://fossa.com to learn more

version: 2
cli:
  server: https://app.fossa.com
  fetcher: custom
  project: https://github.com/puppetlabs/puppetserver
analyze:
  modules:
  - name: project.clj
    type: clojure
    target: project.clj
    path: .
  - name: Gemfile
    type: gem
    target: .
    path: .
  - name: Gemfile
    type: gem
    target: docker
    path: docker
```
4. If possible, a minimal test case reproducing the bug (ideally, a GitHub repository)

**Environment (please complete the following information):**
 - OS: [e.g. Windows] Linux Mint 18.3 Sylvia
 - Are you running in CI?: No
 - Are you running in a Docker image?: No

**Additional context**
