### ISSUE TITLE
Could not upload raw modules

### ISSUE THREAD

**Issue by clover2123** [fossas/fossa-cli#627]
**Describe the bug**
I want to analyze a project which is mainly composed of C++ source codes.
it seems that fossa-cli fails to upload raw modules to the fossa server (other modules work well).
Follow is the warning message I received when I tried to analyze the target.
```
WARNING Could not upload raw module: could not unmarshal JSON API response: invalid character 'U' looking for beginning of value
```
**To Reproduce**
1. Manually create .fossa.yml file to add raw modules (it seems that `fossa init` could not automatically handle raw modules)
2. Run command 
    $ FOSSA_API_KEY=xxxxxxxxxx fossa analyze --server-scan
3. See error

**Expected behavior**
Target source code should be uploaded but it didn't.

**Debugging information**

1. fossa-cli version 1.1.0 (revision 1706109fc9b90f660fcb3dba4d87ab422e1136ff compiled with go version go1.14.7 linux/amd64)
2. `.fossa.yml` file
```
version: 2
cli:
  server: https://app.fossa.com
  fetcher: custom
  project: https://github.com/clover2123/escargot.git
analyze:
  modules:
  - name: src 
    type: raw 
    target: ./src
```

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04
 - Are you running in CI?: No
 - Are you running in a Docker image?: No
