### ISSUE TITLE
Analyze command does not respect the fossa.yml settings

### ISSUE THREAD

**Issue by zenonhun** [fossas/fossa-cli#694]
In our repo there are multiple NPM projects, but nothing else. Only 2 of them which contains production dependencies. 
I have created a .fossa.yml file to narrow down the scope of the analysis:

(I have replaced the folder names with dummy ones)

```
version: 3
targets:
  only:
    - type: npm
    - type: npm
      path: npm-folder1
    - type: npm
      path: npm-folder2
paths:
  only:
    - ./npm-folder1
    - ./npm-folder2
  exclude:
    - ./npm-folder1/node_modules
    - ./npm-folder2/node_modules
```

However fossa still analyses the whole repo for 30+ different languages and takes ages (30+ minutes)
With FossaV1 the same analysis took less than a minute. 

Is there a way to limit the analysis scope somehow?
