### ISSUE TITLE
Remove/deprecate `paths` in `.fossa.yml`

### ISSUE THREAD

**Issue by thernstig** [fossas/fossa-cli#748]
Having both a `targets` and `paths` creates extra cognitive overhead to configure and figure out how the analysis works.

Rather, it would be nice to have:
```yaml
targets:
  exclude:
    - type: ALL
      path: prod/docker
```

This means that `paths` could be deprecated because of the special keyword `ALL`.
