### ISSUE TITLE
`project.id` from `.fossa.yml` not properly respected

### ISSUE THREAD

**Issue by thernstig** [fossas/fossa-cli#751]
Using `fossa-cli version 3.0.12`

Let's say I have this in my `.fossa.yml`:

```yaml
project:
  id: custom+1/projectA
  name: projectA
```

The `project.id` is taken from `Settings -> Project Locator` from the FOSSA web page for the project.

When using `fossa analyze --config .fossa.yml` it outputs:

```sh
[ INFO] Using project name: `custom+1/projectA`
[ INFO] Using revision: `hd61b77c`
[ INFO] Using branch: `fossav3`
[ INFO] ============================================================

      View FOSSA Report:
      https://someurl.com/projects/custom+1%2fcustom+1%2fprojectA/refs/branch/fossav3/hd61b77c
```

Notice how it adds double `custom+1` to the URL.

According to https://github.com/fossas/fossa-cli/blob/master/docs/references/files/fossa-yml.md#projectid the `project.id` should be what is found under the `Settings -> Project Locator`. But then it adds the double `custom+1` as can be seen in the above URL.

If I switch to use:

```yaml
project:
  id: projectA
  name: projectA # Note that this is not needed in reality
```

Then it works. But then I am not using what is visible under `Settings -> Project Locator`.
