### ISSUE TITLE
No analyzed module error not showing up

### ISSUE THREAD

**Issue by xizhao** [fossas/fossa-cli#91]
When we run `fossa report` or `fossa -o`, we get no data or errors from this config.

```
# Generated by FOSSA CLI (https://github.com/fossas/fossa-cli)
# Visit https://fossa.io to learn more
version: 1
cli:
  server: https://app.fossa.io
  project: https://github.com/fossas/fossa-cli.git
  fetcher: custom
analyze: {}
```
